keys:
  - &peter age1d085lpynkxxf0mfus0rd3qq0r38clwz9d5ddrl79x982z00j6qsqq8f54g
  - &system_mns age1s7xs405mkw2gagclktekz27lxhh38se7adrkdfc0x2l28j9xsvdqcdrsyr
  - &system_monitoring age1dpaezlv6va4a8pdqc9w8exuy54d8y2q20yu9zc98q326lusyfdpsf6ph93
  - &system_sync age1ap6uwhhy4uvq72hwyts7gzl027mnypakvj6svphgw2fm8jk72v7qtccs76
  - &system_cache age1tst50yvdtvlggtjcpa47pvywcdaxfv00v04wfwf552wg4wraaexqsaqlke
  - &system_ymir age183wgf8xp46chqk049ekyg7vsan2p50zh4lqfllcllzwuekeywdzqn7pz0q

creation_rules:
  - path_regex: secrets/common.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_mns
      - *system_monitoring
      - *system_sync
      - *system_cache
      - *system_ymir
  
  - path_regex: secrets/[^/]+\.mns.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_mns
  
  - path_regex: secrets/[^/]+\.sync.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_sync

  - path_regex: secrets/monitoring.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_monitoring
  
  - path_regex: secrets/cache.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_cache
  
  - path_regex: secrets/ymir.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_ymir
