keys:
  - &peter age1d085lpynkxxf0mfus0rd3qq0r38clwz9d5ddrl79x982z00j6qsqq8f54g
  - &system_mns age1s7xs405mkw2gagclktekz27lxhh38se7adrkdfc0x2l28j9xsvdqcdrsyr
  - &system_ymir age183wgf8xp46chqk049ekyg7vsan2p50zh4lqfllcllzwuekeywdzqn7pz0q
  - &system_heptifili age1nany90gu4anl7vez3nw7fy0y32vrnp4075dqnc4j9797p44765vsuqzfl5
  - &system_erik age1p6fu4sdzganl8058d8zfecyd8eldjyg4ea2p8xspzpkm5ag8pv5s4rngr7

creation_rules:
  - path_regex: secrets/common.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_mns
      - *system_ymir
      - *system_heptifili
      - *system_erik
  
  - path_regex: secrets/mns.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_mns
  
  - path_regex: secrets/ymir.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_ymir
  
  - path_regex: secrets/heptifili.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_heptifili

  - path_regex: secrets/erik.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter
      - *system_erik
