keys:
  - &peter_kleeblatt age1hczyac0fvxs2uegmvgfld464p2ffqs7wkg3jn2lkmzq4drr5aywqqd376x
  - &peter_sleipnir age1hlpr0fx03wk4q2fk86w6ywm5tw8e0n7k7e850yj73g4n08pf3pxs5rlwz9
  - &system_bjorn age13hre7xupf7jgteufqnxxuam8f6j5p2jeldja4eu4m4nda8r4vprsgzmw37
  - &system_factorio age1haqj7mte6l245ukpn54pxcme6e00as6pv0rwurrusnvzl6vf9f4q544muh
  - &system_heptifili age1hme485ggszkphmky3y0s59r35zmva8jp4awjq8uj6gxc5e7wcvcsx9rg4h
  - &system_ixpect-frankonix age1te0esp3szqwe7vpetcl7njj9e3u32d9s4zuh6m6flqjzpk3zcfrqk6k9mg
  - &system_workstation_server age1dxdta04txkwa25dlzq8rppwrj0ju5e5je0pz0qrek0jz2fs2cc7sym7acy
  - &system_ymir age183wgf8xp46chqk049ekyg7vsan2p50zh4lqfllcllzwuekeywdzqn7pz0q
  - &system_rpki0 age1c0r92htw85wvd5yycqy5hxjumrl27frvvu7eawnlj3yh0fu87qfsehnmer
  - &system_zabbix age1y99qvywte9j2uxjdzewf29wxkp5tngqu49rcq2j7ypmz4gyxpqysuk45ns

creation_rules:
  - path_regex: secrets/common.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_factorio
      - *system_workstation_server
      - *system_ymir
      - *system_heptifili
      - *system_ixpect-frankonix
      - *system_bjorn
      - *system_rpki0
      - *system_zabbix
  
  - path_regex: secrets/factorio.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_factorio

  - path_regex: secrets/workstation-server.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_workstation_server
  
  - path_regex: secrets/ymir.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_ymir
  
  - path_regex: secrets/heptifili.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_heptifili

  - path_regex: secrets/ixpect-frankonix.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_ixpect-frankonix

  - path_regex: secrets/bjorn.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_bjorn
  
  - path_regex: secrets/rpki0.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_rpki0

  - path_regex: secrets/zabbix.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_zabbix
