keys:
  - &peter_kleeblatt age1hczyac0fvxs2uegmvgfld464p2ffqs7wkg3jn2lkmzq4drr5aywqqd376x
  - &peter_sleipnir age1hlpr0fx03wk4q2fk86w6ywm5tw8e0n7k7e850yj73g4n08pf3pxs5rlwz9
  - &system_mns age1s7xs405mkw2gagclktekz27lxhh38se7adrkdfc0x2l28j9xsvdqcdrsyr
  - &system_ymir age183wgf8xp46chqk049ekyg7vsan2p50zh4lqfllcllzwuekeywdzqn7pz0q
  - &system_heptifili age1nany90gu4anl7vez3nw7fy0y32vrnp4075dqnc4j9797p44765vsuqzfl5
  - &system_erik age109jz3m5ct9xz5ywefv7kh26vtep6qucp2msuvxd4jcl0crgqa9dqtml92j
  - &system_router-1 age17lvcj8em2vfn7exr3lwgcr5wrqnq20g3gy2l8l8nxdufw9j879ds2pckw7

creation_rules:
  - path_regex: secrets/common.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_mns
      - *system_ymir
      - *system_heptifili
      - *system_erik
      - *system_router-1
  
  - path_regex: secrets/mns.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_mns
  
  - path_regex: secrets/ymir.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_ymir
  
  - path_regex: secrets/heptifili.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_heptifili

  - path_regex: secrets/erik.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_erik
  
  - path_regex: secrets/router-1.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *peter_kleeblatt
      - *peter_sleipnir
      - *system_router-1
