name: check

on:
  pull_request:

permissions: read-all

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - name: "Run flake checks"
        run: nix flake check --all-systems

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""

      - name: Check format
        run: nix develop --command bash -c 'treefmt --ci -vv'
      - name: Lint using Statix
        run: nix run nixpkgs#statix -- check .
  
  DNS:
    needs: [Check, Lint]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - name: Build DNS config
        run: nix build .#dns
      - name: Deploy DNS config
        run: nix develop --command bash -c 'octodns-sync --config-file result'
        env:
          HETZNER_DNS_API: ${{ secrets.HETZNER_DNS_API }}
  
  Build:
    needs: [Check, Lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - name: Setup NIX Cache
        uses: zombiezen/setup-nix-cache-action@v0.4.0
        with:
          substituters: s3://nix-cache?endpoint=https://nbg1.your-objectstorage.com
          secret_keys: ${{ secrets.NIX_PRIVATE_KEY }}
          aws_access_key_id: ${{ secrets.CACHE_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.CACHE_SECRET_ACCESS_KEY }}
      - name: "Build system configurations"
        run: nix develop --command bash -c 'colmena apply build'
