name: deploy

on:
  push:
    branches:
      - "main"

permissions: read-all

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Run flake checks"
        run: nix flake check --all-systems

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""

      - name: Check format
        run: nix fmt -- --check .
      - name: Lint using Statix
        run: nix run nixpkgs#statix -- check .
  
  DNS:
    needs: [Check, Lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build DNS config
        run: nix build .#dns
      - name: Deploy DNS config
        run: nix develop --command bash -c 'octodns-sync --config-file result --doit'
        env:
          HETZNER_DNS_API: ${{ secrets.HETZNER_DNS_API }}

  # Build:
  #   needs: [Check, Lint]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - name: Setup Nix
  #       uses: DeterminateSystems/nix-installer-action@main
  #       with:
  #         diagnostic-endpoint: ""
  #     - name: Setup Nix cache
  #       uses: DeterminateSystems/magic-nix-cache-action@main
  #     - name: Initialize SSH-Key
  #       uses: webfactory/ssh-agent@v0.9.0
  #       with:
  #         ssh-private-key: ${{ secrets.DEPLOY_KEY }}
  #     - name: Build & push
  #       run: nix develop --command bash -c 'colmena apply push'
  
  # Apply:
  #   needs: [Build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - name: Setup Nix
  #       uses: DeterminateSystems/nix-installer-action@main
  #       with:
  #         diagnostic-endpoint: ""
  #     - name: Setup Nix cache
  #       uses: DeterminateSystems/magic-nix-cache-action@main
  #     - name: Initialize SSH-Key
  #       uses: webfactory/ssh-agent@v0.9.0
  #       with:
  #         ssh-private-key: ${{ secrets.DEPLOY_KEY }}
  #     - name: Build & push
  #       run: nix develop --command bash -c 'colmena apply'
